### ISSUE TITLE
EACCESS error on files upload

### ISSUE THREAD

**Issue by ErmakovDmitriy** [UserOfficeProject/user-office-core#458]
Hi!

We are testing your solution but we have some issues running it in an unprivileged container (which is good from IT security perspective).

When we try to upload files, we get errors as below (some lines are removed as, probably, not related to the issue):

```json
{
    "userMessage": "EACCES: permission denied, mkdir 'downloads'",
    "error": {
        "response": {
            "errors": [
                {
                    "message": "EACCES: permission denied, mkdir 'downloads'",
                    "locations": [
                        {
                            "line": 2,
                            "column": 3
                        }
                    ],
                    "path": [
                        "answerTopic"
                    ],
                    "extensions": {
                        "code": "INTERNAL_SERVER_ERROR"
                    }
                }
            ],
            "data": null,
            "status": 200
    }
}
```

It is not clear for us where the downloads folder is supposed to be located, which access privileges the process must have to work properly and if the `downloads` directory is supposed to be an ephemeral or a persistent storage.

Could you, please, explain for me how the `downloads` directory should be configured?

P.S. Could you, please, tell me if you have a set of Helm charts to deploy the application stack?

**Comment by bolmsten** [comment]
@ErmakovDmitriy  Sorry for not finding this ticket earlier. 

If you see the code here: https://github.com/UserOfficeProject/user-office-core/blob/f842eb6c970207897a6d9a855879233b68e1a009/apps/backend/src/mutations/FileMutations.ts#L32

You can see that it is created runtime by the container. Are you running your container with a less privileged user? We could change so it is created on docker build

**Comment by ErmakovDmitriy** [comment]
Hi! Yes, I mounted a PVC to the path for now though I believe that the directory should be created at build and not during startup.

Moreover, if the directory is created on build, it can be marked as `VOLUME` in Dockerfile and a comment can be added that it is a "temporary" directory.

The same is about "uploads", i.e. `/home/node/app/uploads` path.

**Comment by janosbabik** [comment]
Yes the “uploads” and “downloads” directories are temporary directories used for transient data storage, creating them dynamically within the application is often the most practical and efficient approach. We would like to keep the docker image simple and lean, and “independent” of the applications logic. If you accept my answer then I would close the ticket.
