### ISSUE TITLE
iss parameter is not passed to openid auth server on callback

### ISSUE THREAD

**Issue by darth83** [UserOfficeProject/user-office-core#481]
MAX IV upgraded Keycloak to v23 which caused the problem that we couldn't log in anymore. Keycloak is now adding ```iss``` parameter to the response. See https://www.keycloak.org/docs/23.0.4/upgrading/#added-iss-parameter-to-oauth-2-0openid-connect-authentication-response

When ```"authorization_response_iss_parameter_supported": true``` in the openid configuration (ours is here: https://keycloak.maxiv.lu.se/auth/realms/maxiv/.well-known/openid-configuration) it is required to pass the ```iss``` parameter in the callback, when you get the tokens. This is required by the library openid-client which you are using, https://github.com/panva/node-openid-client/blob/563d9a347a2ddd9aac48ce0d7019f4d5c247864d/lib/client.js#L423

I fixed our issue by adding 
```callbackParams.append('iss', instance.issuer.metadata.issuer);``` here https://github.com/UserOfficeProject/user-office-lib/blob/master/packages/openid/src/OpenIdClient.ts#L21 

I _think_ the correct way would be to get the iss parameter from the auth server at the time of authentification and then pass it through (after validation). Which in turn I think requires a bit of changing in the architecture unfortunately as this parameter is not readily available in the login method.

edit: See https://datatracker.ietf.org/doc/html/rfc9207#section-2.4 for how the validation process of iss parameter should work.

**Comment by martin-trajanovski** [comment]
Hi @darth83 I just opened 2 PRs on the core and on our lib packages that are addressing this issue. Feel free to check and give some comment if needed.

**Comment by darth83** [comment]
Well done! :star:
